<h1><?php echo $this->translate('Sign In'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

$identity = $form->get('identity');
$identity->setAttribute('class', 'form-control');

$credential = $form->get('credential');
$credential->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-default');
?>

<?php echo $this->form()->openTag($form) ?>
<div class="row">
    <div class="col-lg-6">
        <?php
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button><ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>')
                ->render($form->get('identity'))
        ?>
    </div>
</div>
<div class="form-group">
    <div class="col-lg-2 control-label">
        <?php echo $this->formLabel($form->get('identity')) ?>
    </div>
    <div class="col-lg-4">
        <?php echo $this->formInput($form->get('identity')) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-lg-2 col-sm-12 control-label">
        <?php echo $this->formLabel($form->get('credential')) ?>
    </div>
    <div class="col-lg-4 col-sm-12">
        <?php echo $this->formInput($form->get('credential')) ?>
    </div>
</div>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>

<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <?php echo $this->formButton($form->get('submit')) ?>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
    <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>