<div class="bs-docs-section clearfix">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1 id="navbar">First question title</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <p>Here is the fist question that you might want to make</p>
        </div>
        <div class="col-lg-4">
            <div class="well">
                <form class="bs-example form-horizontal">
                    <fieldset>
                        <legend>My answer</legend>
                        <div class="radio">
                            <label>
                                <input type="radio" name="options" id="optionsRadios1" value="1">
                                Option one is this and that&mdash;be sure to include why it's great
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="options" id="optionsRadios2" value="2">
                                Option two can be something else and selecting it will deselect option one
                            </label>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
