<?php echo $this->doctype(); ?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Ääni')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/style.css')
        ?>
        
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')                
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Ääni</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown" id="roomMenu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Voice for <b class="caret"></b></a>
                        <ul class="dropdown-menu" id="room_list">
                           
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" id="roomKey" class="form-control" placeholder="Class key">
                    </div>
                    <button type="submit" class="btn btn-default" id="joinButton">Join</button>
                </form>
            </div>
        </nav>

        <div class="bs-docs-section clearfix">

            <?php echo $this->content; ?>

        </div>
        
    <?php echo $this->inlineScript() ?>
    </body>
</html>