
<div class="row">
    <div class="col-lg-8">
        <h1 id="navbar">First question title</h1>
        <div class="progress progress-striped active">
            <div class="progress-bar" style="width: 45%"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-8">
        <p>Here is the fist question that you might want to make</p>
    </div>
    <div class="col-lg-4">
        <h3>My answer</h3>
        <div class="list-group">
            <a href="#" class="list-group-item active">
                <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
            </a>
            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
            </a>
        </div>

    </div>

</div>
<div class="row">
    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading">First question title</div>
            <p>Here is the fist question that you might want to make</p>

            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">84%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">16%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading">Second question title</div>
            <p>Here is the fist question that you might want to make</p>

            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">13%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">22%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">62%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading">Third question title</div>
            <p>Here is the fist question that you might want to make</p>

            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">74%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">26%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">

    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading">Third question title</div>
            <p>Here is the fist question that you might want to make</p>

            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">74%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">26%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading">First question title</div>
            <p>Here is the fist question that you might want to make</p>

            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">84%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">16%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel">
            <div class="panel-heading">Second question title</div>
            <p>Here is the fist question that you might want to make</p>

            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">13%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto1</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">22%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
                <a href="#" class="list-group-item">
                    <span class="badge">62%</span>
                    <h4 class="list-group-item-heading">Vaihtoehto2</h4>
                    <p class="list-group-item-text">lisää tästä vaihtoehdosta</p>
                </a>
            </div>
        </div>
    </div>
</div>